### ISSUE TITLE
A user can only comment/rate a rate-able one time only!

### ISSUE THREAD

**Issue by AbanoubNassem** [actuallymab/laravel-comment#19]
Currently the user can rate/comment to the same rate-able unlimited times , shouldn't it be one time only?

**Comment by ghost** [comment]
You can try to use a controller and view logic to display comment button
In your controller show method
```
$userid = Auth::user()->id;
$hasCommented = $model->comments()->where('commented_id', $userid)->first();

```
And in your view
```
@if(Auth::user()->id == $hasCommented)
You have already reviewed this model
@else
Show review button
@endelse
```

I'm trying to add a trait so that it can be done more easily with Auth::user()->isFollowing($model)

If i achieve it i will post it as suggestion on this package. Meanwhile you can use the Controller logic above
