### ISSUE TITLE
reply

### ISSUE THREAD

**Issue by whycomeing** [actuallymab/laravel-comment#59]
How to add in this project? 
I don't see any code in 1.0.6

**Comment by LukeMadhanga** [comment]
Yeah this would be a nice feature - removing this package because of this unfortunately. I'd happily add the feature in if needs be

**Comment by LukeMadhanga** [comment]
Just had a look at the issues, it looks like you reply to a Comment #47. Not entirely though

**Comment by LukeMadhanga** [comment]
So what I ended up doing was the following:

Created a new Model called comment with the signature

    use \Actuallymab\LaravelComment\Models\Comment as BaseComment;
    class Comment extends BaseComment { ... }

Updated `config/comments.php` to

    'model' => \App\Models\Comment::class,

In the class, added the protected property `with` so that Laravel eager loads all replies

    protected $with = ['comments'];

This means that you get the replies to the original item in the form

    Post {
        id:
        comments: [
            {
                id
                ...
                comments: [ ...]
            }, 
            ....
        ]
    }

One thing to consider (i don't know how Laravel handles it), is potentially using up all of the nested calls and throwing a fatal error. (i think this is/used to be around 250 nested calls).

**Comment by whycomeing** [comment]
thanks，I know how to do it
